Kmarketer-implementation
Lily-Lilian/BEM-KMarketer pull request #1
Opened 2022-10-06 09:31 UTC by Lily-Lilian

2022-10-06 12:01 UTC, rithaven commented on index.css
> +
remove spaces

2022-10-06 12:01 UTC, rithaven commented on index.css
> +
remove spaces

2022-10-06 12:02 UTC, rithaven commented on index.css
> +
Remove this space

2022-10-06 12:02 UTC, rithaven commented on index.css
> +
Remove spaces

2022-10-06 12:07 UTC, rithaven commented on index.css
> +}
The name of your CSS is confusing. Give it another name "style.css" or other name which differs from it's index.html

2022-10-06 12:11 UTC, rithaven commented on index.html
> +            <div class="footer__menu--sm">Lorem impsum dolor amit</div>
This is a modifier and should not be a class itself

2022-10-06 14:13 UTC, chrisostome01 requested changes
Well done @Lily-Lilian, I left some comments for you, you may check them out

2022-10-06 14:13 UTC, chrisostome01 commented on index.html
> +          <li class="navbar__item">Home</li>
Try to find good name for this element since you have `navbar__items`

2022-10-06 14:13 UTC, chrisostome01 commented on index.html
> +            <svg
Create file for this SVG and use it as an svg

2022-10-06 14:13 UTC, chrisostome01 commented on index.html
> +            <svg
also here create SVG file and use img to display them

2022-10-06 14:13 UTC, chrisostome01 commented on index.css
> +.middle-section__btn {
Locate middle-section and group related styles together

2022-10-06 14:13 UTC, chrisostome01 commented on index.css
> +.title--sm {
same here you can order them like this and this would be good structure
`block` 
`block__element`
`block--modifier`
`block__element--modifier`

2022-10-06 14:13 UTC, chrisostome01 commented on index.css
> +  font-family: "Montserrat";
You can declare this property in `body` so that you won't have to repeat it again

2022-10-06 14:13 UTC, chrisostome01 commented on index.css
> +/* .team-layout__description {
You can delete this style if you are not using them

2022-10-06 14:13 UTC, chrisostome01 commented on index.html
> +            <p>
`p` give it class

2022-10-06 14:13 UTC, chrisostome01 commented on index.html
> +            <p>
same here

2022-10-06 14:13 UTC, sezeranoJchrisostome commented on index.html
> +            <div class="footer__menu">About Us</div>
same here you can improve your namings with this classes `footer__menu` `footer__menus`

2022-10-06 18:28 UTC, sezeranoJchrisostome approved these changes
LGTM

2022-10-07 10:28 UTC, rithaven reviewed
Well Done

2022-10-07 10:34 UTC, rithaven approved these changes

2022-10-09 16:51 UTC, Morrism1 requested changes

2022-10-09 16:51 UTC, Morrism1 commented on index.html
> +          <div class="contact-layaut__agency-content">
You have a typo here with `contact-layaut__agency-content` instead of `contact-layout__agency-content`

2022-10-09 16:51 UTC, Morrism1 commented on index.html
> +            <div>
DIV elements with no class. These are unnecessary.

2022-10-09 16:51 UTC, Morrism1 commented on index.html
> +            <div>
DIV elements with no class. These are unnecessary.

2022-10-09 16:51 UTC, Morrism1 commented on index.html
> +            <div>
DIV elements with no class. These are unnecessary.

2022-10-09 16:51 UTC, Morrism1 commented on index.html
> +            <div>
DIV elements with no class. These are unnecessary.

2022-10-09 16:51 UTC, Morrism1 commented on index.html
> +          <div>
DIV elements with no class. These are unnecessary.

2022-10-09 22:32 UTC, Morrism1 approved these changes
🚀🚀

2022-10-10 06:36 UTC, merged